/*
Deployment script for remdb_etiosa

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "remdb_etiosa"
:setvar DefaultFilePrefix "remdb_etiosa"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_address]...';


GO
ALTER TABLE [dbo].[tbl_address] DROP CONSTRAINT [DF__tbl_addre__dateC__7F2BE32F];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_bank]...';


GO
ALTER TABLE [dbo].[tbl_bank] DROP CONSTRAINT [DF__tbl_bank__dateCr__00200768];


GO
PRINT N'Dropping [dbo].[DF__tbl_batch__dateC__28D80438]...';


GO
ALTER TABLE [dbo].[tbl_batchDownloadRequest] DROP CONSTRAINT [DF__tbl_batch__dateC__28D80438];


GO
PRINT N'Dropping [dbo].[DF__tbl_compa__compa__6991A7CB]...';


GO
ALTER TABLE [dbo].[tbl_company] DROP CONSTRAINT [DF__tbl_compa__compa__6991A7CB];


GO
PRINT N'Dropping [dbo].[DF__tbl_compa__dateC__03F0984C]...';


GO
ALTER TABLE [dbo].[tbl_companyItem] DROP CONSTRAINT [DF__tbl_compa__dateC__03F0984C];


GO
PRINT N'Dropping [dbo].[DF__tbl_conta__dateC__440B1D61]...';


GO
ALTER TABLE [dbo].[tbl_contactDetail] DROP CONSTRAINT [DF__tbl_conta__dateC__440B1D61];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_contactPerson]...';


GO
ALTER TABLE [dbo].[tbl_contactPerson] DROP CONSTRAINT [DF__tbl_conta__dateC__05D8E0BE];


GO
PRINT N'Dropping [dbo].[DF__tbl_deman__dateC__2759D01A]...';


GO
ALTER TABLE [dbo].[tbl_demandnotice] DROP CONSTRAINT [DF__tbl_deman__dateC__2759D01A];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_demandnotice]...';


GO
ALTER TABLE [dbo].[tbl_demandnotice] DROP CONSTRAINT [DF__tbl_deman__isUnb__4AD81681];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_demandNoticeArrears]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticeArrears] DROP CONSTRAINT [DF__tbl_deman__arrea__07C12930];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_demandNoticeArrears]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticeArrears] DROP CONSTRAINT [DF__tbl_deman__dateC__08B54D69];


GO
PRINT N'Dropping [dbo].[DF__tbl_deman__itemA__09A971A2]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticeItem] DROP CONSTRAINT [DF__tbl_deman__itemA__09A971A2];


GO
PRINT N'Dropping [dbo].[DF__tbl_deman__amoun__0A9D95DB]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticeItem] DROP CONSTRAINT [DF__tbl_deman__amoun__0A9D95DB];


GO
PRINT N'Dropping [dbo].[DF__tbl_deman__dateC__0B91BA14]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticeItem] DROP CONSTRAINT [DF__tbl_deman__dateC__0B91BA14];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_demandNoticePaymentHistory]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticePaymentHistory] DROP CONSTRAINT [DF__tbl_deman__amoun__0C85DE4D];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_demandNoticePaymentHistory]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticePaymentHistory] DROP CONSTRAINT [DF__tbl_deman__charg__0D7A0286];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_demandNoticePaymentHistory]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticePaymentHistory] DROP CONSTRAINT [DF__tbl_deman__dateC__0E6E26BF];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_demandNoticePaymentHistory]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticePaymentHistory] DROP CONSTRAINT [DF__tbl_deman__payme__0F624AF8];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_demandNoticePenalty]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticePenalty] DROP CONSTRAINT [DF__tbl_deman__dateC__114A936A];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_demandNoticePenalty]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticePenalty] DROP CONSTRAINT [DF__tbl_deman__itemP__10566F31];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_demandNoticeTaxpayers]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticeTaxpayers] DROP CONSTRAINT [DF__tbl_deman__dateC__123EB7A3];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_demandNoticeTaxpayers]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticeTaxpayers] DROP CONSTRAINT [DF__tbl_deman__deman__67DE6983];


GO
PRINT N'Dropping [dbo].[DF__tbl_domai__datec__1920BF5C]...';


GO
ALTER TABLE [dbo].[tbl_domain] DROP CONSTRAINT [DF__tbl_domai__datec__1920BF5C];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_domain]...';


GO
ALTER TABLE [dbo].[tbl_domain] DROP CONSTRAINT [DF__tbl_domai__domai__14270015];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_domain]...';


GO
ALTER TABLE [dbo].[tbl_domain] DROP CONSTRAINT [DF__tbl_domai__domai__151B244E];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_error]...';


GO
ALTER TABLE [dbo].[tbl_error] DROP CONSTRAINT [DF__tbl_error__dateC__160F4887];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_images]...';


GO
ALTER TABLE [dbo].[tbl_images] DROP CONSTRAINT [DF__tbl_image__dateC__17036CC0];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_item]...';


GO
ALTER TABLE [dbo].[tbl_item] DROP CONSTRAINT [DF__tbl_item__dateCr__18EBB532];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_item]...';


GO
ALTER TABLE [dbo].[tbl_item] DROP CONSTRAINT [DF__tbl_item__itemSt__17F790F9];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_itempenalty]...';


GO
ALTER TABLE [dbo].[tbl_itempenalty] DROP CONSTRAINT [DF__tbl_itemp__amoun__1BC821DD];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_itempenalty]...';


GO
ALTER TABLE [dbo].[tbl_itempenalty] DROP CONSTRAINT [DF__tbl_itemp__dateC__1CBC4616];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_itempenalty]...';


GO
ALTER TABLE [dbo].[tbl_itempenalty] DROP CONSTRAINT [DF__tbl_itemp__penal__1AD3FDA4];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_lcda]...';


GO
ALTER TABLE [dbo].[tbl_lcda] DROP CONSTRAINT [DF__tbl_lcda__charge__1F98B2C1];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_lcda]...';


GO
ALTER TABLE [dbo].[tbl_lcda] DROP CONSTRAINT [DF__tbl_lcda__dateCr__1DB06A4F];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_lcda]...';


GO
ALTER TABLE [dbo].[tbl_lcda] DROP CONSTRAINT [DF__tbl_lcda__lcdaSt__1EA48E88];


GO
PRINT N'Dropping [dbo].[DF_LcdaProperty_propertyStatus]...';


GO
ALTER TABLE [dbo].[tbl_LcdaProperty] DROP CONSTRAINT [DF_LcdaProperty_propertyStatus];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_prepayment]...';


GO
ALTER TABLE [dbo].[tbl_prepayment] DROP CONSTRAINT [DF__tbl_prepa__prepa__63A3C44B];


GO
PRINT N'Dropping [dbo].[DF_tbl_role_roleStatus]...';


GO
ALTER TABLE [dbo].[tbl_role] DROP CONSTRAINT [DF_tbl_role_roleStatus];


GO
PRINT N'Dropping [dbo].[DF__tbl_secto__dateC__2C88998B]...';


GO
ALTER TABLE [dbo].[tbl_sector] DROP CONSTRAINT [DF__tbl_secto__dateC__2C88998B];


GO
PRINT N'Dropping [dbo].[DF__tbl_stree__dateC__66603565]...';


GO
ALTER TABLE [dbo].[tbl_street] DROP CONSTRAINT [DF__tbl_stree__dateC__66603565];


GO
PRINT N'Dropping [dbo].[DF__tbl_stree__stree__00AA174D]...';


GO
ALTER TABLE [dbo].[tbl_street] DROP CONSTRAINT [DF__tbl_stree__stree__00AA174D];


GO
PRINT N'Dropping [dbo].[DF__tbl_taxPa__dateC__6E565CE8]...';


GO
ALTER TABLE [dbo].[tbl_taxPayer] DROP CONSTRAINT [DF__tbl_taxPa__dateC__6E565CE8];


GO
PRINT N'Dropping [dbo].[DF_tbl_taxPayer_taxpayerStatus]...';


GO
ALTER TABLE [dbo].[tbl_taxPayer] DROP CONSTRAINT [DF_tbl_taxPayer_taxpayerStatus];


GO
PRINT N'Dropping [dbo].[DF__tbl_taxpa__dateC__3429BB53]...';


GO
ALTER TABLE [dbo].[tbl_taxpayerCategory] DROP CONSTRAINT [DF__tbl_taxpa__dateC__3429BB53];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_users]...';


GO
ALTER TABLE [dbo].[tbl_users] DROP CONSTRAINT [DF__tbl_users__dateC__2A164134];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_users]...';


GO
ALTER TABLE [dbo].[tbl_users] DROP CONSTRAINT [DF__tbl_users__gende__2B0A656D];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_users]...';


GO
ALTER TABLE [dbo].[tbl_users] DROP CONSTRAINT [DF__tbl_users__userS__29221CFB];


GO
PRINT N'Dropping [dbo].[DF__tbl_ward__dateCr__4E53A1AA]...';


GO
ALTER TABLE [dbo].[tbl_ward] DROP CONSTRAINT [DF__tbl_ward__dateCr__4E53A1AA];


GO
PRINT N'Dropping [dbo].[DF__tbl_ward__wardSt__4D5F7D71]...';


GO
ALTER TABLE [dbo].[tbl_ward] DROP CONSTRAINT [DF__tbl_ward__wardSt__4D5F7D71];


GO
PRINT N'Dropping [dbo].[DF__tbl_compa__amoun__02FC7413]...';


GO
ALTER TABLE [dbo].[tbl_companyItem] DROP CONSTRAINT [DF__tbl_compa__amoun__02FC7413];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_demandNoticePaymentHistory]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticePaymentHistory] DROP CONSTRAINT [DF__tbl_deman__syncS__58671BC9];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_demandNoticePaymentHistory]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticePaymentHistory] DROP CONSTRAINT [DF__tbl_deman__IsWai__60C757A0];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_demandNoticeTaxpayers]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticeTaxpayers] DROP CONSTRAINT [DF__tbl_deman__isUnb__4BCC3ABA];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_itempenalty]...';


GO
ALTER TABLE [dbo].[tbl_itempenalty] DROP CONSTRAINT [DF__tbl_itemp__isPer__19DFD96B];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_users]...';


GO
ALTER TABLE [dbo].[tbl_users] DROP CONSTRAINT [DF__tbl_users__locke__282DF8C2];


GO
PRINT N'Dropping [dbo].[FK__tbl_deman__dn_ta__2EDAF651]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticeItem] DROP CONSTRAINT [FK__tbl_deman__dn_ta__2EDAF651];


GO
PRINT N'Dropping [dbo].[FK__tbl_deman__itemI__2FCF1A8A]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticeItem] DROP CONSTRAINT [FK__tbl_deman__itemI__2FCF1A8A];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_userlcda]...';


GO
ALTER TABLE [dbo].[tbl_userlcda] DROP CONSTRAINT [FK__tbl_userl__lgdai__3C34F16F];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_userlcda]...';


GO
ALTER TABLE [dbo].[tbl_userlcda] DROP CONSTRAINT [FK__tbl_userl__useri__3D2915A8];


GO
PRINT N'Dropping [dbo].[FK__tbl_userR__rolei__6B24EA82]...';


GO
ALTER TABLE [dbo].[tbl_userRole] DROP CONSTRAINT [FK__tbl_userR__rolei__6B24EA82];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_userRole]...';


GO
ALTER TABLE [dbo].[tbl_userRole] DROP CONSTRAINT [FK__tbl_userR__useri__3F115E1A];


GO
PRINT N'Dropping [dbo].[FK__tbl_taxPa__compa__6C6E1476]...';


GO
ALTER TABLE [dbo].[tbl_taxPayer] DROP CONSTRAINT [FK__tbl_taxPa__compa__6C6E1476];


GO
PRINT N'Dropping [dbo].[FK__tbl_compa__itemI__2DE6D218]...';


GO
ALTER TABLE [dbo].[tbl_companyItem] DROP CONSTRAINT [FK__tbl_compa__itemI__2DE6D218];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_state]...';


GO
ALTER TABLE [dbo].[tbl_state] DROP CONSTRAINT [FK__tbl_state__count__367C1819];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_userdomain]...';


GO
ALTER TABLE [dbo].[tbl_userdomain] DROP CONSTRAINT [FK__tbl_userd__domai__3A4CA8FD];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_itempenalty]...';


GO
ALTER TABLE [dbo].[tbl_itempenalty] DROP CONSTRAINT [FK__tbl_itemp__itemI__31B762FC];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_item]...';


GO
ALTER TABLE [dbo].[tbl_item] DROP CONSTRAINT [FK__tbl_item__lcdaId__30C33EC3];


GO
PRINT N'Dropping [dbo].[FK__tbl_role__lgda__20C1E124]...';


GO
ALTER TABLE [dbo].[tbl_role] DROP CONSTRAINT [FK__tbl_role__lgda__20C1E124];


GO
PRINT N'Dropping [dbo].[FK__tbl_secto__lcdaI__2B947552]...';


GO
ALTER TABLE [dbo].[tbl_sector] DROP CONSTRAINT [FK__tbl_secto__lcdaI__2B947552];


GO
PRINT N'Dropping [dbo].[FK__tbl_ward__lcdaId__3D5E1FD2]...';


GO
ALTER TABLE [dbo].[tbl_ward] DROP CONSTRAINT [FK__tbl_ward__lcdaId__3D5E1FD2];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_rolePermission]...';


GO
ALTER TABLE [dbo].[tbl_rolePermission] DROP CONSTRAINT [FK__tbl_roleP__permi__339FAB6E];


GO
PRINT N'Dropping [dbo].[FK__tbl_roleP__roleI__33D4B598]...';


GO
ALTER TABLE [dbo].[tbl_rolePermission] DROP CONSTRAINT [FK__tbl_roleP__roleI__33D4B598];


GO
PRINT N'Dropping [dbo].[FK__tbl_taxPa__stree__6D6238AF]...';


GO
ALTER TABLE [dbo].[tbl_taxPayer] DROP CONSTRAINT [FK__tbl_taxPa__stree__6D6238AF];


GO
PRINT N'Dropping [dbo].[FK__tbl_stree__wardI__656C112C]...';


GO
ALTER TABLE [dbo].[tbl_street] DROP CONSTRAINT [FK__tbl_stree__wardI__656C112C];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_userdomain]...';


GO
ALTER TABLE [dbo].[tbl_userdomain] DROP CONSTRAINT [FK__tbl_userd__useri__3B40CD36];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_country]...';


GO
ALTER TABLE [dbo].[tbl_country] DROP CONSTRAINT [UQ__tbl_coun__A09D7FE25C885AED];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_country]...';


GO
ALTER TABLE [dbo].[tbl_country] DROP CONSTRAINT [UQ__tbl_coun__0756ED8C77A004A9];


GO
PRINT N'Dropping [dbo].[UQ__tbl_doma__ED9877D744120E9A]...';


GO
ALTER TABLE [dbo].[tbl_domain] DROP CONSTRAINT [UQ__tbl_doma__ED9877D744120E9A];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_permission]...';


GO
ALTER TABLE [dbo].[tbl_permission] DROP CONSTRAINT [UQ__tbl_perm__70661EFC34E936C2];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_state]...';


GO
ALTER TABLE [dbo].[tbl_state] DROP CONSTRAINT [UQ__tbl_stat__E7485CE4E7CC90CB];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_state]...';


GO
ALTER TABLE [dbo].[tbl_state] DROP CONSTRAINT [UQ__tbl_stat__8B97A9603D741FA7];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_users]...';


GO
ALTER TABLE [dbo].[tbl_users] DROP CONSTRAINT [UQ__tbl_user__AB6E6164010835D9];


GO
PRINT N'Dropping unnamed constraint on [dbo].[tbl_users]...';


GO
ALTER TABLE [dbo].[tbl_users] DROP CONSTRAINT [UQ__tbl_user__F3DBC572E9FC7C9D];


GO
PRINT N'Dropping [dbo].[PK_tbl_DemandNoticeDownloadHistory]...';


GO
ALTER TABLE [dbo].[tbl_DemandNoticeDownloadHistory] DROP CONSTRAINT [PK_tbl_DemandNoticeDownloadHistory];


GO
PRINT N'Dropping <unnamed>...';


GO
EXECUTE sp_droprolemember @rolename = N'db_owner', @membername = N'IIS APPPOOL\remsngAppPool';


GO
PRINT N'Starting rebuilding table [dbo].[tbl_address]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_address] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [Addressnumber]    NVARCHAR (MAX)   NULL,
    [StreetId]         UNIQUEIDENTIFIER NULL,
    [CreatedBy]        NVARCHAR (MAX)   NULL,
    [DateCreated]      DATETIME2 (7)    NULL,
    [Lastmodifiedby]   NVARCHAR (MAX)   NULL,
    [LastModifiedDate] DATETIME2 (7)    NULL,
    [OwnerId]          UNIQUEIDENTIFIER NOT NULL,
    [Lcdaid]           UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_address1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_address])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_address] ([Id], [addressnumber], [streetId], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate], [ownerId], [lcdaid])
        SELECT   [Id],
                 [addressnumber],
                 [streetId],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate],
                 [ownerId],
                 [lcdaid]
        FROM     [dbo].[tbl_address]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_address];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_address]', N'tbl_address';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_address1]', N'PK_tbl_address', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_address].[IX_tbl_address_OwnerId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_address_OwnerId]
    ON [dbo].[tbl_address]([OwnerId] ASC);


GO
PRINT N'Creating [dbo].[tbl_address].[IX_tbl_address_StreetId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_address_StreetId]
    ON [dbo].[tbl_address]([StreetId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_bank]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_bank] (
    [Id]          UNIQUEIDENTIFIER NOT NULL,
    [BankName]    NVARCHAR (MAX)   NULL,
    [DateCreated] DATETIME2 (7)    NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_bank1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_bank])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_bank] ([Id], [bankName], [dateCreated])
        SELECT   [Id],
                 [bankName],
                 [dateCreated]
        FROM     [dbo].[tbl_bank]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_bank];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_bank]', N'tbl_bank';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_bank1]', N'PK_tbl_bank', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Altering [dbo].[tbl_bank_lcda]...';


GO
ALTER TABLE [dbo].[tbl_bank_lcda] ALTER COLUMN [bankAccount] NVARCHAR (MAX) NULL;

ALTER TABLE [dbo].[tbl_bank_lcda] ALTER COLUMN [bankId] UNIQUEIDENTIFIER NOT NULL;

ALTER TABLE [dbo].[tbl_bank_lcda] ALTER COLUMN [lcdaId] UNIQUEIDENTIFIER NOT NULL;


GO
PRINT N'Creating [dbo].[tbl_bank_lcda].[IX_tbl_bank_lcda_BankId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_bank_lcda_BankId]
    ON [dbo].[tbl_bank_lcda]([BankId] ASC);


GO
PRINT N'Creating [dbo].[tbl_bank_lcda].[IX_tbl_bank_lcda_LcdaId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_bank_lcda_LcdaId]
    ON [dbo].[tbl_bank_lcda]([LcdaId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_batchDownloadRequest]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_batchDownloadRequest] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [BatchNo]          NVARCHAR (MAX)   NULL,
    [RequestStatus]    NVARCHAR (MAX)   NULL,
    [LcdaId]           UNIQUEIDENTIFIER NULL,
    [BatchFileName]    NVARCHAR (MAX)   NULL,
    [Createdby]        NVARCHAR (MAX)   NULL,
    [DateCreated]      DATETIME2 (7)    NOT NULL,
    [Lastmodifiedby]   NVARCHAR (MAX)   NULL,
    [LastModifiedDate] DATETIME2 (7)    NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_batchDownloadRequest1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_batchDownloadRequest])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_batchDownloadRequest] ([Id], [batchNo], [requestStatus], [lcdaId], [batchFileName], [createdby], [dateCreated], [lastmodifiedby], [lastModifiedDate])
        SELECT   [Id],
                 [batchNo],
                 [requestStatus],
                 [lcdaId],
                 [batchFileName],
                 [createdby],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate]
        FROM     [dbo].[tbl_batchDownloadRequest]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_batchDownloadRequest];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_batchDownloadRequest]', N'tbl_batchDownloadRequest';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_batchDownloadRequest1]', N'PK_tbl_batchDownloadRequest', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[tbl_company]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_company] (
    [Id]                 UNIQUEIDENTIFIER NOT NULL,
    [CompanyName]        NVARCHAR (MAX)   NULL,
    [StreetId]           UNIQUEIDENTIFIER NULL,
    [SectorId]           UNIQUEIDENTIFIER NULL,
    [AddressId]          UNIQUEIDENTIFIER NULL,
    [CategoryId]         UNIQUEIDENTIFIER NULL,
    [CompanyStatus]      NVARCHAR (MAX)   NULL,
    [CreatedBy]          NVARCHAR (MAX)   NULL,
    [DateCreated]        DATETIME2 (7)    NULL,
    [Lastmodifiedby]     NVARCHAR (MAX)   NULL,
    [LastModifiedDate]   DATETIME2 (7)    NULL,
    [LcdaId]             UNIQUEIDENTIFIER NOT NULL,
    [TaxPayerCatgeoryId] UNIQUEIDENTIFIER NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_company1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_company])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_company] ([Id], [companyName], [streetId], [sectorId], [addressId], [categoryId], [companyStatus], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate], [lcdaId])
        SELECT   [Id],
                 [companyName],
                 [streetId],
                 [sectorId],
                 [addressId],
                 [categoryId],
                 [companyStatus],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate],
                 [lcdaId]
        FROM     [dbo].[tbl_company]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_company];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_company]', N'tbl_company';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_company1]', N'PK_tbl_company', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_company].[IX_tbl_company_TaxPayerCatgeoryId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_company_TaxPayerCatgeoryId]
    ON [dbo].[tbl_company]([TaxPayerCatgeoryId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_companyItem]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_companyItem] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [TaxpayerId]       UNIQUEIDENTIFIER NOT NULL,
    [ItemId]           UNIQUEIDENTIFIER NOT NULL,
    [Amount]           DECIMAL (18, 2)  NOT NULL,
    [BillingYear]      INT              NOT NULL,
    [CreatedBy]        NVARCHAR (MAX)   NULL,
    [DateCreated]      DATETIME2 (7)    NOT NULL,
    [Lastmodifiedby]   NVARCHAR (MAX)   NULL,
    [LastModifiedDate] DATETIME2 (7)    NULL,
    [CompanyStatus]    NVARCHAR (MAX)   NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_companyItem1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_companyItem])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_companyItem] ([Id], [taxpayerId], [itemId], [amount], [billingYear], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate], [companyStatus])
        SELECT   [Id],
                 [taxpayerId],
                 [itemId],
                 [amount],
                 [billingYear],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate],
                 [companyStatus]
        FROM     [dbo].[tbl_companyItem]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_companyItem];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_companyItem]', N'tbl_companyItem';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_companyItem1]', N'PK_tbl_companyItem', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_companyItem].[IX_tbl_companyItem_ItemId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_companyItem_ItemId]
    ON [dbo].[tbl_companyItem]([ItemId] ASC);


GO
PRINT N'Creating [dbo].[tbl_companyItem].[IX_tbl_companyItem_TaxpayerId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_companyItem_TaxpayerId]
    ON [dbo].[tbl_companyItem]([TaxpayerId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_contactDetail]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_contactDetail] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [OwnerId]          UNIQUEIDENTIFIER NOT NULL,
    [ContactValue]     NVARCHAR (MAX)   NULL,
    [ContactType]      NVARCHAR (MAX)   NULL,
    [CreatedBy]        NVARCHAR (MAX)   NULL,
    [DateCreated]      DATETIME2 (7)    NULL,
    [Lastmodifiedby]   NVARCHAR (MAX)   NULL,
    [LastModifiedDate] DATETIME2 (7)    NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_contactDetail1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_contactDetail])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_contactDetail] ([Id], [ownerId], [contactValue], [contactType], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate])
        SELECT   [Id],
                 [ownerId],
                 [contactValue],
                 [contactType],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate]
        FROM     [dbo].[tbl_contactDetail]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_contactDetail];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_contactDetail]', N'tbl_contactDetail';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_contactDetail1]', N'PK_tbl_contactDetail', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[tbl_contactPerson]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_contactPerson] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [Surname]          NVARCHAR (MAX)   NULL,
    [Firstname]        NVARCHAR (MAX)   NULL,
    [Lastname]         NVARCHAR (MAX)   NULL,
    [TaxPayerId]       UNIQUEIDENTIFIER NULL,
    [CreatedBy]        NVARCHAR (MAX)   NULL,
    [DateCreated]      DATETIME2 (7)    NULL,
    [Lastmodifiedby]   NVARCHAR (MAX)   NULL,
    [LastModifiedDate] DATETIME2 (7)    NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_contactPerson1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_contactPerson])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_contactPerson] ([Id], [surname], [firstname], [lastname], [taxPayerId], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate])
        SELECT   [Id],
                 [surname],
                 [firstname],
                 [lastname],
                 [taxPayerId],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate]
        FROM     [dbo].[tbl_contactPerson]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_contactPerson];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_contactPerson]', N'tbl_contactPerson';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_contactPerson1]', N'PK_tbl_contactPerson', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[tbl_country]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_country] (
    [Id]          UNIQUEIDENTIFIER NOT NULL,
    [CountryName] NVARCHAR (MAX)   NULL,
    [CountryCode] NVARCHAR (MAX)   NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_country1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_country])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_country] ([Id], [countryName], [countryCode])
        SELECT   [Id],
                 [countryName],
                 [countryCode]
        FROM     [dbo].[tbl_country]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_country];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_country]', N'tbl_country';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_country1]', N'PK_tbl_country', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
/*
The column DateCreated on table [dbo].[tbl_demandnotice] must be changed from NULL to NOT NULL. If the table contains data, the ALTER script may not work. To avoid this issue, you must add values to this column for all rows or mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/
GO
PRINT N'Starting rebuilding table [dbo].[tbl_demandnotice]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_demandnotice] (
    [Id]                 UNIQUEIDENTIFIER NOT NULL,
    [Query]              NVARCHAR (MAX)   NULL,
    [PlainTextQuery]     NVARCHAR (MAX)   NULL,
    [BatchNo]            NVARCHAR (MAX)   NULL,
    [DemandNoticeStatus] NVARCHAR (MAX)   NULL,
    [BillingYear]        INT              NOT NULL,
    [LcdaId]             UNIQUEIDENTIFIER NOT NULL,
    [CreatedBy]          NVARCHAR (MAX)   NULL,
    [DateCreated]        DATETIME2 (7)    NOT NULL,
    [Lastmodifiedby]     NVARCHAR (MAX)   NULL,
    [LastModifiedDate]   DATETIME2 (7)    NULL,
    [WardId]             UNIQUEIDENTIFIER NULL,
    [StreetId]           UNIQUEIDENTIFIER NULL,
    [IsUnbilled]         BIT              NOT NULL,
    [RowVersion]         ROWVERSION       NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_demandnotice1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_demandnotice])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_demandnotice] ([Id], [query], [batchNo], [demandNoticeStatus], [billingYear], [lcdaId], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate], [wardId], [streetId], [isUnbilled])
        SELECT   [Id],
                 [query],
                 [batchNo],
                 [demandNoticeStatus],
                 [billingYear],
                 [lcdaId],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate],
                 [wardId],
                 [streetId],
                 [isUnbilled]
        FROM     [dbo].[tbl_demandnotice]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_demandnotice];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_demandnotice]', N'tbl_demandnotice';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_demandnotice1]', N'PK_tbl_demandnotice', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_demandnotice].[IX_tbl_demandnotice_StreetId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_demandnotice_StreetId]
    ON [dbo].[tbl_demandnotice]([StreetId] ASC);


GO
PRINT N'Creating [dbo].[tbl_demandnotice].[IX_tbl_demandnotice_WardId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_demandnotice_WardId]
    ON [dbo].[tbl_demandnotice]([WardId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_demandNoticeArrears]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_demandNoticeArrears] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [BillingNo]        NVARCHAR (MAX)   NULL,
    [TaxpayerId]       UNIQUEIDENTIFIER NOT NULL,
    [TotalAmount]      DECIMAL (18, 2)  NOT NULL,
    [AmountPaid]       DECIMAL (18, 2)  NOT NULL,
    [ItemId]           UNIQUEIDENTIFIER NOT NULL,
    [OriginatedYear]   INT              NOT NULL,
    [BillingYear]      INT              NOT NULL,
    [ArrearsStatus]    NVARCHAR (MAX)   NULL,
    [CreatedBy]        NVARCHAR (MAX)   NULL,
    [DateCreated]      DATETIME2 (7)    NULL,
    [Lastmodifiedby]   NVARCHAR (MAX)   NULL,
    [LastModifiedDate] DATETIME2 (7)    NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_demandNoticeArrears1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_demandNoticeArrears])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_demandNoticeArrears] ([Id], [billingNo], [taxpayerId], [totalAmount], [amountPaid], [itemId], [originatedYear], [billingYear], [arrearsStatus], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate])
        SELECT   [Id],
                 [billingNo],
                 [taxpayerId],
                 [totalAmount],
                 [amountPaid],
                 [itemId],
                 [originatedYear],
                 [billingYear],
                 [arrearsStatus],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate]
        FROM     [dbo].[tbl_demandNoticeArrears]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_demandNoticeArrears];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_demandNoticeArrears]', N'tbl_demandNoticeArrears';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_demandNoticeArrears1]', N'PK_tbl_demandNoticeArrears', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_demandNoticeArrears].[IX_tbl_demandNoticeArrears_ItemId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_demandNoticeArrears_ItemId]
    ON [dbo].[tbl_demandNoticeArrears]([ItemId] ASC);


GO
PRINT N'Creating [dbo].[tbl_demandNoticeArrears].[IX_tbl_demandNoticeArrears_TaxpayerId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_demandNoticeArrears_TaxpayerId]
    ON [dbo].[tbl_demandNoticeArrears]([TaxpayerId] ASC);


GO
PRINT N'Altering [dbo].[tbl_DemandNoticeDownloadHistory]...';


GO
ALTER TABLE [dbo].[tbl_DemandNoticeDownloadHistory] ALTER COLUMN [billingNumber] NVARCHAR (MAX) NULL;

ALTER TABLE [dbo].[tbl_DemandNoticeDownloadHistory] ALTER COLUMN [createdBy] NVARCHAR (MAX) NULL;

ALTER TABLE [dbo].[tbl_DemandNoticeDownloadHistory] ALTER COLUMN [dateCreated] DATETIME2 (7) NULL;

ALTER TABLE [dbo].[tbl_DemandNoticeDownloadHistory] ALTER COLUMN [lastmodifiedby] NVARCHAR (MAX) NULL;

ALTER TABLE [dbo].[tbl_DemandNoticeDownloadHistory] ALTER COLUMN [lastModifiedDate] DATETIME2 (7) NULL;


GO
PRINT N'Creating [dbo].[PK_tbl_DemandNoticeDownloadHistory]...';


GO
ALTER TABLE [dbo].[tbl_DemandNoticeDownloadHistory]
    ADD CONSTRAINT [PK_tbl_DemandNoticeDownloadHistory] PRIMARY KEY CLUSTERED ([Id] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_demandNoticeItem]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_demandNoticeItem] (
    [Id]                    UNIQUEIDENTIFIER NOT NULL,
    [BillingNo]             NVARCHAR (MAX)   NULL,
    [dn_taxpayersDetailsId] UNIQUEIDENTIFIER NOT NULL,
    [DemandNoticeId]        UNIQUEIDENTIFIER NULL,
    [TaxpayerId]            UNIQUEIDENTIFIER NOT NULL,
    [ItemId]                UNIQUEIDENTIFIER NOT NULL,
    [ItemName]              NVARCHAR (MAX)   NULL,
    [ItemAmount]            DECIMAL (18, 2)  NOT NULL,
    [AmountPaid]            DECIMAL (18, 2)  NOT NULL,
    [ItemStatus]            NVARCHAR (MAX)   NULL,
    [CreatedBy]             NVARCHAR (MAX)   NULL,
    [DateCreated]           DATETIME2 (7)    NULL,
    [Lastmodifiedby]        NVARCHAR (MAX)   NULL,
    [LastModifiedDate]      DATETIME2 (7)    NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_demandNoticeItem1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_demandNoticeItem])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_demandNoticeItem] ([Id], [billingNo], [dn_taxpayersDetailsId], [taxpayerId], [itemId], [itemName], [itemAmount], [amountPaid], [itemStatus], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate])
        SELECT   [Id],
                 [billingNo],
                 [dn_taxpayersDetailsId],
                 [taxpayerId],
                 [itemId],
                 [itemName],
                 [itemAmount],
                 [amountPaid],
                 [itemStatus],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate]
        FROM     [dbo].[tbl_demandNoticeItem]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_demandNoticeItem];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_demandNoticeItem]', N'tbl_demandNoticeItem';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_demandNoticeItem1]', N'PK_tbl_demandNoticeItem', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_demandNoticeItem].[IX_tbl_demandNoticeItem_ItemId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_demandNoticeItem_ItemId]
    ON [dbo].[tbl_demandNoticeItem]([ItemId] ASC);


GO
PRINT N'Creating [dbo].[tbl_demandNoticeItem].[IX_tbl_demandNoticeItem_TaxpayerId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_demandNoticeItem_TaxpayerId]
    ON [dbo].[tbl_demandNoticeItem]([TaxpayerId] ASC);


GO
PRINT N'Creating [dbo].[tbl_demandNoticeItem].[IX_tbl_demandNoticeItem_dn_taxpayersDetailsId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_demandNoticeItem_dn_taxpayersDetailsId]
    ON [dbo].[tbl_demandNoticeItem]([dn_taxpayersDetailsId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_demandNoticePaymentHistory]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_demandNoticePaymentHistory] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [OwnerId]          UNIQUEIDENTIFIER NOT NULL,
    [BillingNumber]    NVARCHAR (MAX)   NULL,
    [Amount]           DECIMAL (18, 2)  NOT NULL,
    [Charges]          DECIMAL (18, 2)  NOT NULL,
    [PaymentMode]      NVARCHAR (MAX)   NULL,
    [ReferenceNumber]  NVARCHAR (MAX)   NULL,
    [BankId]           UNIQUEIDENTIFIER NOT NULL,
    [CreatedBy]        NVARCHAR (MAX)   NULL,
    [DateCreated]      DATETIME2 (7)    NULL,
    [Lastmodifiedby]   NVARCHAR (MAX)   NULL,
    [LastModifiedDate] DATETIME2 (7)    NULL,
    [PaymentStatus]    NVARCHAR (MAX)   NULL,
    [SyncStatus]       BIT              NOT NULL,
    [IsWaiver]         BIT              NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_demandNoticePaymentHistory1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_demandNoticePaymentHistory])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_demandNoticePaymentHistory] ([Id], [ownerId], [billingNumber], [amount], [charges], [paymentMode], [referenceNumber], [bankId], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate], [paymentStatus], [syncStatus], [IsWaiver])
        SELECT   [Id],
                 [ownerId],
                 [billingNumber],
                 [amount],
                 [charges],
                 [paymentMode],
                 [referenceNumber],
                 [bankId],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate],
                 [paymentStatus],
                 [syncStatus],
                 [IsWaiver]
        FROM     [dbo].[tbl_demandNoticePaymentHistory]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_demandNoticePaymentHistory];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_demandNoticePaymentHistory]', N'tbl_demandNoticePaymentHistory';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_demandNoticePaymentHistory1]', N'PK_tbl_demandNoticePaymentHistory', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_demandNoticePaymentHistory].[IX_tbl_demandNoticePaymentHistory_BankId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_demandNoticePaymentHistory_BankId]
    ON [dbo].[tbl_demandNoticePaymentHistory]([BankId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_demandNoticePenalty]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_demandNoticePenalty] (
    [Id]                UNIQUEIDENTIFIER NOT NULL,
    [BillingNo]         NVARCHAR (MAX)   NULL,
    [TaxpayerId]        UNIQUEIDENTIFIER NOT NULL,
    [TotalAmount]       DECIMAL (18, 2)  NOT NULL,
    [AmountPaid]        DECIMAL (18, 2)  NOT NULL,
    [ItemId]            UNIQUEIDENTIFIER NOT NULL,
    [OriginatedYear]    INT              NOT NULL,
    [BillingYear]       INT              NOT NULL,
    [ItemPenaltyStatus] NVARCHAR (MAX)   NULL,
    [CreatedBy]         NVARCHAR (MAX)   NULL,
    [DateCreated]       DATETIME2 (7)    NULL,
    [Lastmodifiedby]    NVARCHAR (MAX)   NULL,
    [LastModifiedDate]  DATETIME2 (7)    NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_demandNoticePenalty1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_demandNoticePenalty])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_demandNoticePenalty] ([Id], [billingNo], [taxpayerId], [totalAmount], [amountPaid], [itemId], [originatedYear], [billingYear], [itemPenaltyStatus], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate])
        SELECT   [Id],
                 [billingNo],
                 [taxpayerId],
                 [totalAmount],
                 [amountPaid],
                 [itemId],
                 [originatedYear],
                 [billingYear],
                 [itemPenaltyStatus],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate]
        FROM     [dbo].[tbl_demandNoticePenalty]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_demandNoticePenalty];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_demandNoticePenalty]', N'tbl_demandNoticePenalty';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_demandNoticePenalty1]', N'PK_tbl_demandNoticePenalty', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_demandNoticePenalty].[IX_tbl_demandNoticePenalty_ItemId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_demandNoticePenalty_ItemId]
    ON [dbo].[tbl_demandNoticePenalty]([ItemId] ASC);


GO
PRINT N'Creating [dbo].[tbl_demandNoticePenalty].[IX_tbl_demandNoticePenalty_TaxpayerId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_demandNoticePenalty_TaxpayerId]
    ON [dbo].[tbl_demandNoticePenalty]([TaxpayerId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_demandNoticeTaxpayers]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_demandNoticeTaxpayers] (
    [Id]                       UNIQUEIDENTIFIER NOT NULL,
    [DnId]                     UNIQUEIDENTIFIER NOT NULL,
    [TaxpayerId]               UNIQUEIDENTIFIER NOT NULL,
    [TaxpayersName]            NVARCHAR (MAX)   NULL,
    [BillingNumber]            NVARCHAR (MAX)   NULL,
    [AddressName]              NVARCHAR (MAX)   NULL,
    [WardName]                 NVARCHAR (MAX)   NULL,
    [LcdaName]                 NVARCHAR (MAX)   NULL,
    [BillingYr]                INT              NOT NULL,
    [DomainName]               NVARCHAR (MAX)   NULL,
    [LcdaAddress]              NVARCHAR (MAX)   NULL,
    [LcdaState]                NVARCHAR (MAX)   NULL,
    [LcdaLogoFileName]         NVARCHAR (MAX)   NULL,
    [CouncilTreasurerSigFilen] NVARCHAR (MAX)   NULL,
    [RevCoodinatorSigFilen]    NVARCHAR (MAX)   NULL,
    [CouncilTreasurerMobile]   NVARCHAR (MAX)   NULL,
    [CreatedBy]                NVARCHAR (MAX)   NULL,
    [DateCreated]              DATETIME2 (7)    NULL,
    [Lastmodifiedby]           NVARCHAR (MAX)   NULL,
    [LastModifiedDate]         DATETIME2 (7)    NULL,
    [DemandNoticeStatus]       NVARCHAR (MAX)   NULL,
    [IsUnbilled]               BIT              NOT NULL,
    [Period]                   INT              NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_demandNoticeTaxpayers1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_demandNoticeTaxpayers])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_demandNoticeTaxpayers] ([Id], [dnId], [taxpayerId], [taxpayersName], [billingNumber], [addressName], [wardName], [lcdaName], [billingYr], [domainName], [lcdaAddress], [lcdaState], [lcdaLogoFileName], [councilTreasurerSigFilen], [revCoodinatorSigFilen], [councilTreasurerMobile], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate], [demandNoticeStatus], [isUnbilled])
        SELECT   [Id],
                 [dnId],
                 [taxpayerId],
                 [taxpayersName],
                 [billingNumber],
                 [addressName],
                 [wardName],
                 [lcdaName],
                 [billingYr],
                 [domainName],
                 [lcdaAddress],
                 [lcdaState],
                 [lcdaLogoFileName],
                 [councilTreasurerSigFilen],
                 [revCoodinatorSigFilen],
                 [councilTreasurerMobile],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate],
                 [demandNoticeStatus],
                 [isUnbilled]
        FROM     [dbo].[tbl_demandNoticeTaxpayers]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_demandNoticeTaxpayers];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_demandNoticeTaxpayers]', N'tbl_demandNoticeTaxpayers';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_demandNoticeTaxpayers1]', N'PK_tbl_demandNoticeTaxpayers', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_demandNoticeTaxpayers].[IX_tbl_demandNoticeTaxpayers_DnId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_demandNoticeTaxpayers_DnId]
    ON [dbo].[tbl_demandNoticeTaxpayers]([DnId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_domain]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_domain] (
    [Id]           UNIQUEIDENTIFIER NOT NULL,
    [DomainName]   NVARCHAR (MAX)   NULL,
    [DomainCode]   NVARCHAR (MAX)   NULL,
    [Datecreated]  DATETIME2 (7)    NOT NULL,
    [AddressId]    UNIQUEIDENTIFIER NULL,
    [DomainStatus] NVARCHAR (MAX)   NULL,
    [DomainType]   NVARCHAR (MAX)   NULL,
    [StateId]      UNIQUEIDENTIFIER NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_domain1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_domain])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_domain] ([Id], [domainName], [domainCode], [datecreated], [addressId], [domainStatus], [domainType], [stateId])
        SELECT   [Id],
                 [domainName],
                 [domainCode],
                 [datecreated],
                 [addressId],
                 [domainStatus],
                 [domainType],
                 [stateId]
        FROM     [dbo].[tbl_domain]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_domain];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_domain]', N'tbl_domain';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_domain1]', N'PK_tbl_domain', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_domain].[IX_tbl_domain_StateId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_domain_StateId]
    ON [dbo].[tbl_domain]([StateId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_error]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_error] (
    [Id]          UNIQUEIDENTIFIER NOT NULL,
    [ErrorType]   NVARCHAR (MAX)   NULL,
    [Errorvalue]  NVARCHAR (MAX)   NULL,
    [DateCreated] DATETIME2 (7)    NULL,
    [OwnerId]     UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_error1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_error])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_error] ([Id], [errorType], [errorvalue], [dateCreated], [ownerId])
        SELECT   [Id],
                 [errorType],
                 [errorvalue],
                 [dateCreated],
                 [ownerId]
        FROM     [dbo].[tbl_error]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_error];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_error]', N'tbl_error';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_error1]', N'PK_tbl_error', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[tbl_images]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_images] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [ImgFilename]      NVARCHAR (MAX)   NULL,
    [OwnerId]          UNIQUEIDENTIFIER NOT NULL,
    [ImgType]          NVARCHAR (MAX)   NULL,
    [CreatedBy]        NVARCHAR (MAX)   NULL,
    [DateCreated]      DATETIME2 (7)    NULL,
    [Lastmodifiedby]   NVARCHAR (MAX)   NULL,
    [LastModifiedDate] DATETIME2 (7)    NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_images1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_images])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_images] ([Id], [imgFilename], [ownerId], [imgType], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate])
        SELECT   [Id],
                 [imgFilename],
                 [ownerId],
                 [imgType],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate]
        FROM     [dbo].[tbl_images]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_images];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_images]', N'tbl_images';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_images1]', N'PK_tbl_images', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[tbl_item]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_item] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [ItemDescription]  NVARCHAR (MAX)   NULL,
    [ItemStatus]       NVARCHAR (MAX)   NULL,
    [LcdaId]           UNIQUEIDENTIFIER NOT NULL,
    [CreatedBy]        NVARCHAR (MAX)   NULL,
    [DateCreated]      DATETIME2 (7)    NULL,
    [Lastmodifiedby]   NVARCHAR (MAX)   NULL,
    [LastModifiedDate] DATETIME2 (7)    NULL,
    [ItemCode]         NVARCHAR (MAX)   NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_item1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_item])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_item] ([Id], [itemDescription], [itemStatus], [lcdaId], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate], [itemCode])
        SELECT   [Id],
                 [itemDescription],
                 [itemStatus],
                 [lcdaId],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate],
                 [itemCode]
        FROM     [dbo].[tbl_item]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_item];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_item]', N'tbl_item';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_item1]', N'PK_tbl_item', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_item].[IX_tbl_item_LcdaId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_item_LcdaId]
    ON [dbo].[tbl_item]([LcdaId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_itempenalty]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_itempenalty] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [ItemId]           UNIQUEIDENTIFIER NOT NULL,
    [IsPercentage]     BIT              NOT NULL,
    [PenaltyStatus]    NVARCHAR (MAX)   NULL,
    [Amount]           DECIMAL (18, 2)  NOT NULL,
    [Duration]         NVARCHAR (MAX)   NULL,
    [CreatedBy]        NVARCHAR (MAX)   NULL,
    [DateCreated]      DATETIME2 (7)    NULL,
    [Lastmodifiedby]   NVARCHAR (MAX)   NULL,
    [LastModifiedDate] DATETIME2 (7)    NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_itempenalty1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_itempenalty])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_itempenalty] ([Id], [itemId], [isPercentage], [penaltyStatus], [amount], [duration], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate])
        SELECT   [Id],
                 [itemId],
                 [isPercentage],
                 [penaltyStatus],
                 [amount],
                 [duration],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate]
        FROM     [dbo].[tbl_itempenalty]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_itempenalty];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_itempenalty]', N'tbl_itempenalty';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_itempenalty1]', N'PK_tbl_itempenalty', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_itempenalty].[IX_tbl_itempenalty_ItemId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_itempenalty_ItemId]
    ON [dbo].[tbl_itempenalty]([ItemId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_lcda]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_lcda] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [DomainId]         UNIQUEIDENTIFIER NOT NULL,
    [LcdaName]         NVARCHAR (MAX)   NULL,
    [LcdaCode]         NVARCHAR (MAX)   NULL,
    [AddressId]        UNIQUEIDENTIFIER NOT NULL,
    [CreatedBy]        NVARCHAR (MAX)   NULL,
    [DateCreated]      DATETIME2 (7)    NULL,
    [Lastmodifiedby]   NVARCHAR (MAX)   NULL,
    [LastModifiedDate] DATETIME2 (7)    NULL,
    [LcdaStatus]       NVARCHAR (MAX)   NULL,
    [Charges]          DECIMAL (18, 2)  NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_lcda1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_lcda])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_lcda] ([Id], [domainId], [lcdaName], [lcdaCode], [addressId], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate], [lcdaStatus], [charges])
        SELECT   [Id],
                 [domainId],
                 [lcdaName],
                 [lcdaCode],
                 [addressId],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate],
                 [lcdaStatus],
                 [charges]
        FROM     [dbo].[tbl_lcda]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_lcda];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_lcda]', N'tbl_lcda';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_lcda1]', N'PK_tbl_lcda', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_lcda].[IX_tbl_lcda_DomainId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_lcda_DomainId]
    ON [dbo].[tbl_lcda]([DomainId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_LcdaProperty]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_LcdaProperty] (
    [Id]             UNIQUEIDENTIFIER NOT NULL,
    [PropertyKey]    NVARCHAR (MAX)   NULL,
    [PropertyValue]  NVARCHAR (MAX)   NULL,
    [LcdaId]         UNIQUEIDENTIFIER NOT NULL,
    [PropertyStatus] NVARCHAR (MAX)   NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_LcdaProperty1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_LcdaProperty])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_LcdaProperty] ([Id], [propertyKey], [propertyValue], [lcdaId], [propertyStatus])
        SELECT   [Id],
                 [propertyKey],
                 [propertyValue],
                 [lcdaId],
                 [propertyStatus]
        FROM     [dbo].[tbl_LcdaProperty]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_LcdaProperty];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_LcdaProperty]', N'tbl_LcdaProperty';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_LcdaProperty1]', N'PK_tbl_LcdaProperty', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[tbl_permission]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_permission] (
    [Id]                    UNIQUEIDENTIFIER NOT NULL,
    [PermissionName]        NVARCHAR (MAX)   NULL,
    [PermissionDescription] NVARCHAR (MAX)   NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_permission1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_permission])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_permission] ([Id], [permissionName], [permissionDescription])
        SELECT   [Id],
                 [permissionName],
                 [permissionDescription]
        FROM     [dbo].[tbl_permission]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_permission];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_permission]', N'tbl_permission';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_permission1]', N'PK_tbl_permission', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[tbl_prepayment]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_prepayment] (
    [id]               BIGINT           IDENTITY (1, 1) NOT NULL,
    [taxpayerId]       UNIQUEIDENTIFIER NOT NULL,
    [amount]           DECIMAL (18, 2)  NOT NULL,
    [datecreated]      DATETIME2 (7)    NOT NULL,
    [prepaymentStatus] NVARCHAR (MAX)   NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_prepayment1] PRIMARY KEY CLUSTERED ([id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_prepayment])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_tbl_prepayment] ON;
        INSERT INTO [dbo].[tmp_ms_xx_tbl_prepayment] ([id], [taxpayerId], [amount], [prepaymentStatus], [datecreated])
        SELECT   [id],
                 [taxpayerId],
                 [amount],
                 [prepaymentStatus],
                 [datecreated]
        FROM     [dbo].[tbl_prepayment]
        ORDER BY [id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_tbl_prepayment] OFF;
    END

DROP TABLE [dbo].[tbl_prepayment];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_prepayment]', N'tbl_prepayment';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_prepayment1]', N'PK_tbl_prepayment', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[tbl_role]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_role] (
    [Id]         UNIQUEIDENTIFIER NOT NULL,
    [RoleName]   NVARCHAR (MAX)   NULL,
    [DomainId]   UNIQUEIDENTIFIER NOT NULL,
    [RoleStatus] NVARCHAR (MAX)   NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_role1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_role])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_role] ([Id], [roleName], [domainId], [roleStatus])
        SELECT   [Id],
                 [roleName],
                 [domainId],
                 [roleStatus]
        FROM     [dbo].[tbl_role]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_role];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_role]', N'tbl_role';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_role1]', N'PK_tbl_role', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_role].[IX_tbl_role_DomainId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_role_DomainId]
    ON [dbo].[tbl_role]([DomainId] ASC);


GO
PRINT N'Altering [dbo].[tbl_sector]...';


GO
ALTER TABLE [dbo].[tbl_sector] ALTER COLUMN [createdBy] NVARCHAR (MAX) NULL;

ALTER TABLE [dbo].[tbl_sector] ALTER COLUMN [dateCreated] DATETIME2 (7) NOT NULL;

ALTER TABLE [dbo].[tbl_sector] ALTER COLUMN [lastmodifiedby] NVARCHAR (MAX) NULL;

ALTER TABLE [dbo].[tbl_sector] ALTER COLUMN [lastModifiedDate] DATETIME2 (7) NULL;

ALTER TABLE [dbo].[tbl_sector] ALTER COLUMN [prefix] NVARCHAR (MAX) NULL;

ALTER TABLE [dbo].[tbl_sector] ALTER COLUMN [sectorName] NVARCHAR (MAX) NULL;


GO
PRINT N'Creating [dbo].[tbl_sector].[IX_tbl_sector_LcdaId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_sector_LcdaId]
    ON [dbo].[tbl_sector]([LcdaId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_state]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_state] (
    [Id]        UNIQUEIDENTIFIER NOT NULL,
    [CountryId] UNIQUEIDENTIFIER NOT NULL,
    [StateCode] NVARCHAR (MAX)   NULL,
    [StateName] NVARCHAR (MAX)   NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_state1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_state])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_state] ([Id], [countryId], [stateCode], [stateName])
        SELECT   [Id],
                 [countryId],
                 [stateCode],
                 [stateName]
        FROM     [dbo].[tbl_state]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_state];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_state]', N'tbl_state';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_state1]', N'PK_tbl_state', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_state].[IX_tbl_state_CountryId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_state_CountryId]
    ON [dbo].[tbl_state]([CountryId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_street]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_street] (
    [Id]                UNIQUEIDENTIFIER NOT NULL,
    [WardId]            UNIQUEIDENTIFIER NOT NULL,
    [StreetName]        NVARCHAR (MAX)   NULL,
    [NumberOfHouse]     INT              NULL,
    [CreatedBy]         NVARCHAR (MAX)   NULL,
    [DateCreated]       DATETIME2 (7)    NULL,
    [Lastmodifiedby]    NVARCHAR (MAX)   NULL,
    [LastModifiedDate]  DATETIME2 (7)    NULL,
    [StreetStatus]      NVARCHAR (MAX)   NULL,
    [StreetDescription] NVARCHAR (MAX)   NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_street1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_street])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_street] ([Id], [wardId], [streetName], [numberOfHouse], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate], [streetStatus], [streetDescription])
        SELECT   [Id],
                 [wardId],
                 [streetName],
                 [numberOfHouse],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate],
                 [streetStatus],
                 [streetDescription]
        FROM     [dbo].[tbl_street]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_street];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_street]', N'tbl_street';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_street1]', N'PK_tbl_street', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_street].[IX_tbl_street_WardId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_street_WardId]
    ON [dbo].[tbl_street]([WardId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_taxPayer]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_taxPayer] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [CompanyId]        UNIQUEIDENTIFIER NOT NULL,
    [StreetId]         UNIQUEIDENTIFIER NULL,
    [AddressId]        UNIQUEIDENTIFIER NULL,
    [CreatedBy]        NVARCHAR (MAX)   NULL,
    [DateCreated]      DATETIME2 (7)    NULL,
    [Lastmodifiedby]   NVARCHAR (MAX)   NULL,
    [LastModifiedDate] DATETIME2 (7)    NULL,
    [TaxpayerStatus]   NVARCHAR (MAX)   NULL,
    [Surname]          NVARCHAR (MAX)   NULL,
    [Firstname]        NVARCHAR (MAX)   NULL,
    [Lastname]         NVARCHAR (MAX)   NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_taxPayer1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_taxPayer])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_taxPayer] ([Id], [companyId], [streetId], [addressId], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate], [taxpayerStatus], [surname], [firstname], [lastname])
        SELECT   [Id],
                 [companyId],
                 [streetId],
                 [addressId],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate],
                 [taxpayerStatus],
                 [surname],
                 [firstname],
                 [lastname]
        FROM     [dbo].[tbl_taxPayer]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_taxPayer];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_taxPayer]', N'tbl_taxPayer';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_taxPayer1]', N'PK_tbl_taxPayer', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_taxPayer].[IX_tbl_taxPayer_AddressId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_tbl_taxPayer_AddressId]
    ON [dbo].[tbl_taxPayer]([AddressId] ASC) WHERE ([AddressId] IS NOT NULL);


GO
PRINT N'Creating [dbo].[tbl_taxPayer].[IX_tbl_taxPayer_CompanyId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_taxPayer_CompanyId]
    ON [dbo].[tbl_taxPayer]([CompanyId] ASC);


GO
PRINT N'Creating [dbo].[tbl_taxPayer].[IX_tbl_taxPayer_StreetId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_taxPayer_StreetId]
    ON [dbo].[tbl_taxPayer]([StreetId] ASC);


GO
PRINT N'Altering [dbo].[tbl_taxpayerCategory]...';


GO
ALTER TABLE [dbo].[tbl_taxpayerCategory] ALTER COLUMN [createdBy] NVARCHAR (MAX) NULL;

ALTER TABLE [dbo].[tbl_taxpayerCategory] ALTER COLUMN [dateCreated] DATETIME2 (7) NOT NULL;

ALTER TABLE [dbo].[tbl_taxpayerCategory] ALTER COLUMN [lastmodifiedby] NVARCHAR (MAX) NULL;

ALTER TABLE [dbo].[tbl_taxpayerCategory] ALTER COLUMN [lastModifiedDate] DATETIME2 (7) NULL;

ALTER TABLE [dbo].[tbl_taxpayerCategory] ALTER COLUMN [taxpayerCategoryName] NVARCHAR (MAX) NULL;


GO
PRINT N'Starting rebuilding table [dbo].[tbl_userlcda]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_userlcda] (
    [LgdaId] UNIQUEIDENTIFIER NOT NULL,
    [UserId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_userlcda1] PRIMARY KEY CLUSTERED ([UserId] ASC, [LgdaId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_userlcda])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_userlcda] ([UserId], [LgdaId])
        SELECT   [UserId],
                 [LgdaId]
        FROM     [dbo].[tbl_userlcda]
        ORDER BY [UserId] ASC, [LgdaId] ASC;
    END

DROP TABLE [dbo].[tbl_userlcda];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_userlcda]', N'tbl_userlcda';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_userlcda1]', N'PK_tbl_userlcda', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_userlcda].[IX_tbl_userlcda_LgdaId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_userlcda_LgdaId]
    ON [dbo].[tbl_userlcda]([LgdaId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_userRole]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_userRole] (
    [RoleId] UNIQUEIDENTIFIER NOT NULL,
    [UserId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_userRole1] PRIMARY KEY CLUSTERED ([UserId] ASC, [RoleId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_userRole])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_userRole] ([UserId], [RoleId])
        SELECT   [UserId],
                 [RoleId]
        FROM     [dbo].[tbl_userRole]
        ORDER BY [UserId] ASC, [RoleId] ASC;
    END

DROP TABLE [dbo].[tbl_userRole];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_userRole]', N'tbl_userRole';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_userRole1]', N'PK_tbl_userRole', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_userRole].[IX_tbl_userRole_RoleId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_userRole_RoleId]
    ON [dbo].[tbl_userRole]([RoleId] ASC);


GO
PRINT N'Starting rebuilding table [dbo].[tbl_users]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_users] (
    [Id]                  UNIQUEIDENTIFIER NOT NULL,
    [Email]               NVARCHAR (MAX)   NULL,
    [PasswordHash]        NVARCHAR (MAX)   NULL,
    [SecurityStamp]       NVARCHAR (MAX)   NULL,
    [LockedOutEndDateUtc] DATETIME2 (7)    NULL,
    [Lockedoutenabled]    BIT              NULL,
    [Username]            NVARCHAR (MAX)   NULL,
    [UserStatus]          NVARCHAR (MAX)   NULL,
    [CreatedBy]           NVARCHAR (MAX)   NULL,
    [DateCreated]         DATETIME2 (7)    NULL,
    [Lastmodifiedby]      NVARCHAR (MAX)   NULL,
    [LastModifiedDate]    DATETIME2 (7)    NULL,
    [Lastname]            NVARCHAR (MAX)   NULL,
    [Surname]             NVARCHAR (MAX)   NULL,
    [Firstname]           NVARCHAR (MAX)   NULL,
    [Gender]              NVARCHAR (MAX)   NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_users1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_users])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_users] ([Id], [email], [passwordHash], [securityStamp], [lockedOutEndDateUTC], [lockedoutenabled], [username], [userStatus], [createdBy], [dateCreated], [lastmodifiedby], [lastModifiedDate], [lastname], [surname], [firstname], [gender])
        SELECT   [Id],
                 [email],
                 [passwordHash],
                 [securityStamp],
                 [lockedOutEndDateUTC],
                 [lockedoutenabled],
                 [username],
                 [userStatus],
                 [createdBy],
                 [dateCreated],
                 [lastmodifiedby],
                 [lastModifiedDate],
                 [lastname],
                 [surname],
                 [firstname],
                 [gender]
        FROM     [dbo].[tbl_users]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_users];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_users]', N'tbl_users';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_users1]', N'PK_tbl_users', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[tbl_ward]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tbl_ward] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [WardName]         NVARCHAR (MAX)   NULL,
    [LcdaId]           UNIQUEIDENTIFIER NOT NULL,
    [WardStatus]       NVARCHAR (MAX)   NULL,
    [CreatedBy]        NVARCHAR (MAX)   NULL,
    [Lastmodifiedby]   NVARCHAR (MAX)   NULL,
    [DateCreated]      DATETIME2 (7)    NOT NULL,
    [LastModifiedDate] DATETIME2 (7)    NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tbl_ward1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tbl_ward])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tbl_ward] ([Id], [wardName], [lcdaId], [wardStatus], [createdBy], [lastmodifiedby], [dateCreated], [lastModifiedDate])
        SELECT   [Id],
                 [wardName],
                 [lcdaId],
                 [wardStatus],
                 [createdBy],
                 [lastmodifiedby],
                 [dateCreated],
                 [lastModifiedDate]
        FROM     [dbo].[tbl_ward]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[tbl_ward];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tbl_ward]', N'tbl_ward';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tbl_ward1]', N'PK_tbl_ward', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[tbl_ward].[IX_tbl_ward_LcdaId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_ward_LcdaId]
    ON [dbo].[tbl_ward]([LcdaId] ASC);


GO
PRINT N'Creating [dbo].[__EFMigrationsHistory]...';


GO
CREATE TABLE [dbo].[__EFMigrationsHistory] (
    [MigrationId]    NVARCHAR (150) NOT NULL,
    [ProductVersion] NVARCHAR (32)  NOT NULL,
    CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED ([MigrationId] ASC)
);


GO
PRINT N'Creating [dbo].[tbl_cloudData]...';


GO
CREATE TABLE [dbo].[tbl_cloudData] (
    [Id]            UNIQUEIDENTIFIER NOT NULL,
    [DomainId]      UNIQUEIDENTIFIER NOT NULL,
    [DataTitle]     NVARCHAR (MAX)   NULL,
    [SyncStatus]    NVARCHAR (MAX)   NULL,
    [JsonContent]   NVARCHAR (MAX)   NULL,
    [BillingNumber] NVARCHAR (MAX)   NULL,
    [DateCreated]   DATETIME2 (7)    NULL,
    CONSTRAINT [PK_tbl_cloudData] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[PK_tbl_rolePermission]...';


GO
ALTER TABLE [dbo].[tbl_rolePermission]
    ADD CONSTRAINT [PK_tbl_rolePermission] PRIMARY KEY CLUSTERED ([RoleId] ASC, [PermissionId] ASC);


GO
PRINT N'Creating [dbo].[PK_tbl_userdomain]...';


GO
ALTER TABLE [dbo].[tbl_userdomain]
    ADD CONSTRAINT [PK_tbl_userdomain] PRIMARY KEY CLUSTERED ([UserId] ASC, [DomainId] ASC);


GO
PRINT N'Creating [dbo].[tbl_rolePermission].[IX_tbl_rolePermission_PermissionId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_rolePermission_PermissionId]
    ON [dbo].[tbl_rolePermission]([PermissionId] ASC);


GO
PRINT N'Creating [dbo].[tbl_userdomain].[IX_tbl_userdomain_DomainId]...';


GO
CREATE NONCLUSTERED INDEX [IX_tbl_userdomain_DomainId]
    ON [dbo].[tbl_userdomain]([DomainId] ASC);


GO
PRINT N'Creating [dbo].[FK_tbl_demandnotice_tbl_street_StreetId]...';


GO
ALTER TABLE [dbo].[tbl_demandnotice] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_demandnotice_tbl_street_StreetId] FOREIGN KEY ([StreetId]) REFERENCES [dbo].[tbl_street] ([Id]);


GO
PRINT N'Creating [dbo].[FK_tbl_demandnotice_tbl_ward_WardId]...';


GO
ALTER TABLE [dbo].[tbl_demandnotice] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_demandnotice_tbl_ward_WardId] FOREIGN KEY ([WardId]) REFERENCES [dbo].[tbl_ward] ([Id]);


GO
PRINT N'Creating [dbo].[FK_tbl_demandNoticeItem_tbl_item_ItemId]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticeItem] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_demandNoticeItem_tbl_item_ItemId] FOREIGN KEY ([ItemId]) REFERENCES [dbo].[tbl_item] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_demandNoticeItem_tbl_taxPayer_TaxpayerId]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticeItem] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_demandNoticeItem_tbl_taxPayer_TaxpayerId] FOREIGN KEY ([TaxpayerId]) REFERENCES [dbo].[tbl_taxPayer] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_demandNoticeItem_tbl_demandNoticeTaxpayers_dn_taxpayersDetailsId]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticeItem] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_demandNoticeItem_tbl_demandNoticeTaxpayers_dn_taxpayersDetailsId] FOREIGN KEY ([dn_taxpayersDetailsId]) REFERENCES [dbo].[tbl_demandNoticeTaxpayers] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_userlcda_tbl_lcda_LgdaId]...';


GO
ALTER TABLE [dbo].[tbl_userlcda] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_userlcda_tbl_lcda_LgdaId] FOREIGN KEY ([LgdaId]) REFERENCES [dbo].[tbl_lcda] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_userlcda_tbl_users_UserId]...';


GO
ALTER TABLE [dbo].[tbl_userlcda] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_userlcda_tbl_users_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[tbl_users] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_userRole_tbl_role_RoleId]...';


GO
ALTER TABLE [dbo].[tbl_userRole] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_userRole_tbl_role_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[tbl_role] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_userRole_tbl_users_UserId]...';


GO
ALTER TABLE [dbo].[tbl_userRole] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_userRole_tbl_users_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[tbl_users] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_address_tbl_taxPayer_OwnerId]...';


GO
ALTER TABLE [dbo].[tbl_address] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_address_tbl_taxPayer_OwnerId] FOREIGN KEY ([OwnerId]) REFERENCES [dbo].[tbl_taxPayer] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_company_tbl_taxpayerCategory_TaxPayerCatgeoryId]...';


GO
ALTER TABLE [dbo].[tbl_company] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_company_tbl_taxpayerCategory_TaxPayerCatgeoryId] FOREIGN KEY ([TaxPayerCatgeoryId]) REFERENCES [dbo].[tbl_taxpayerCategory] ([Id]);


GO
PRINT N'Creating [dbo].[FK_tbl_companyItem_tbl_item_ItemId]...';


GO
ALTER TABLE [dbo].[tbl_companyItem] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_companyItem_tbl_item_ItemId] FOREIGN KEY ([ItemId]) REFERENCES [dbo].[tbl_item] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_companyItem_tbl_taxPayer_TaxpayerId]...';


GO
ALTER TABLE [dbo].[tbl_companyItem] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_companyItem_tbl_taxPayer_TaxpayerId] FOREIGN KEY ([TaxpayerId]) REFERENCES [dbo].[tbl_taxPayer] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_demandNoticeArrears_tbl_item_ItemId]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticeArrears] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_demandNoticeArrears_tbl_item_ItemId] FOREIGN KEY ([ItemId]) REFERENCES [dbo].[tbl_item] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_demandNoticeArrears_tbl_taxPayer_TaxpayerId]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticeArrears] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_demandNoticeArrears_tbl_taxPayer_TaxpayerId] FOREIGN KEY ([TaxpayerId]) REFERENCES [dbo].[tbl_taxPayer] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_demandNoticePaymentHistory_tbl_bank_BankId]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticePaymentHistory] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_demandNoticePaymentHistory_tbl_bank_BankId] FOREIGN KEY ([BankId]) REFERENCES [dbo].[tbl_bank] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_demandNoticePenalty_tbl_item_ItemId]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticePenalty] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_demandNoticePenalty_tbl_item_ItemId] FOREIGN KEY ([ItemId]) REFERENCES [dbo].[tbl_item] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_demandNoticePenalty_tbl_taxPayer_TaxpayerId]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticePenalty] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_demandNoticePenalty_tbl_taxPayer_TaxpayerId] FOREIGN KEY ([TaxpayerId]) REFERENCES [dbo].[tbl_taxPayer] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_demandNoticeTaxpayers_tbl_demandnotice_DnId]...';


GO
ALTER TABLE [dbo].[tbl_demandNoticeTaxpayers] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_demandNoticeTaxpayers_tbl_demandnotice_DnId] FOREIGN KEY ([DnId]) REFERENCES [dbo].[tbl_demandnotice] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_domain_tbl_state_StateId]...';


GO
ALTER TABLE [dbo].[tbl_domain] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_domain_tbl_state_StateId] FOREIGN KEY ([StateId]) REFERENCES [dbo].[tbl_state] ([Id]);


GO
PRINT N'Creating [dbo].[FK_tbl_item_tbl_lcda_LcdaId]...';


GO
ALTER TABLE [dbo].[tbl_item] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_item_tbl_lcda_LcdaId] FOREIGN KEY ([LcdaId]) REFERENCES [dbo].[tbl_lcda] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_itempenalty_tbl_item_ItemId]...';


GO
ALTER TABLE [dbo].[tbl_itempenalty] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_itempenalty_tbl_item_ItemId] FOREIGN KEY ([ItemId]) REFERENCES [dbo].[tbl_item] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_lcda_tbl_domain_DomainId]...';


GO
ALTER TABLE [dbo].[tbl_lcda] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_lcda_tbl_domain_DomainId] FOREIGN KEY ([DomainId]) REFERENCES [dbo].[tbl_domain] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_role_tbl_lcda_DomainId]...';


GO
ALTER TABLE [dbo].[tbl_role] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_role_tbl_lcda_DomainId] FOREIGN KEY ([DomainId]) REFERENCES [dbo].[tbl_lcda] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_state_tbl_country_CountryId]...';


GO
ALTER TABLE [dbo].[tbl_state] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_state_tbl_country_CountryId] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[tbl_country] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_street_tbl_ward_WardId]...';


GO
ALTER TABLE [dbo].[tbl_street] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_street_tbl_ward_WardId] FOREIGN KEY ([WardId]) REFERENCES [dbo].[tbl_ward] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_taxPayer_tbl_company_CompanyId]...';


GO
ALTER TABLE [dbo].[tbl_taxPayer] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_taxPayer_tbl_company_CompanyId] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[tbl_company] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_taxPayer_tbl_street_StreetId]...';


GO
ALTER TABLE [dbo].[tbl_taxPayer] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_taxPayer_tbl_street_StreetId] FOREIGN KEY ([StreetId]) REFERENCES [dbo].[tbl_street] ([Id]);


GO
PRINT N'Creating [dbo].[FK_tbl_taxPayer_tbl_address_AddressId]...';


GO
ALTER TABLE [dbo].[tbl_taxPayer] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_taxPayer_tbl_address_AddressId] FOREIGN KEY ([AddressId]) REFERENCES [dbo].[tbl_address] ([Id]);


GO
PRINT N'Creating [dbo].[FK_tbl_ward_tbl_lcda_LcdaId]...';


GO
ALTER TABLE [dbo].[tbl_ward] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_ward_tbl_lcda_LcdaId] FOREIGN KEY ([LcdaId]) REFERENCES [dbo].[tbl_lcda] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_bank_lcda_tbl_bank_BankId]...';


GO
ALTER TABLE [dbo].[tbl_bank_lcda] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_bank_lcda_tbl_bank_BankId] FOREIGN KEY ([BankId]) REFERENCES [dbo].[tbl_bank] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_bank_lcda_tbl_lcda_LcdaId]...';


GO
ALTER TABLE [dbo].[tbl_bank_lcda] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_bank_lcda_tbl_lcda_LcdaId] FOREIGN KEY ([LcdaId]) REFERENCES [dbo].[tbl_lcda] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_rolePermission_tbl_permission_PermissionId]...';


GO
ALTER TABLE [dbo].[tbl_rolePermission] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_rolePermission_tbl_permission_PermissionId] FOREIGN KEY ([PermissionId]) REFERENCES [dbo].[tbl_permission] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_rolePermission_tbl_role_RoleId]...';


GO
ALTER TABLE [dbo].[tbl_rolePermission] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_rolePermission_tbl_role_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[tbl_role] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_sector_tbl_lcda_LcdaId]...';


GO
ALTER TABLE [dbo].[tbl_sector] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_sector_tbl_lcda_LcdaId] FOREIGN KEY ([LcdaId]) REFERENCES [dbo].[tbl_lcda] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_userdomain_tbl_domain_DomainId]...';


GO
ALTER TABLE [dbo].[tbl_userdomain] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_userdomain_tbl_domain_DomainId] FOREIGN KEY ([DomainId]) REFERENCES [dbo].[tbl_domain] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_tbl_userdomain_tbl_users_UserId]...';


GO
ALTER TABLE [dbo].[tbl_userdomain] WITH NOCHECK
    ADD CONSTRAINT [FK_tbl_userdomain_tbl_users_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[tbl_users] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[tbl_demandnotice] WITH CHECK CHECK CONSTRAINT [FK_tbl_demandnotice_tbl_street_StreetId];

ALTER TABLE [dbo].[tbl_demandnotice] WITH CHECK CHECK CONSTRAINT [FK_tbl_demandnotice_tbl_ward_WardId];

ALTER TABLE [dbo].[tbl_demandNoticeItem] WITH CHECK CHECK CONSTRAINT [FK_tbl_demandNoticeItem_tbl_item_ItemId];

ALTER TABLE [dbo].[tbl_demandNoticeItem] WITH CHECK CHECK CONSTRAINT [FK_tbl_demandNoticeItem_tbl_taxPayer_TaxpayerId];

ALTER TABLE [dbo].[tbl_demandNoticeItem] WITH CHECK CHECK CONSTRAINT [FK_tbl_demandNoticeItem_tbl_demandNoticeTaxpayers_dn_taxpayersDetailsId];

ALTER TABLE [dbo].[tbl_userlcda] WITH CHECK CHECK CONSTRAINT [FK_tbl_userlcda_tbl_lcda_LgdaId];

ALTER TABLE [dbo].[tbl_userlcda] WITH CHECK CHECK CONSTRAINT [FK_tbl_userlcda_tbl_users_UserId];

ALTER TABLE [dbo].[tbl_userRole] WITH CHECK CHECK CONSTRAINT [FK_tbl_userRole_tbl_role_RoleId];

ALTER TABLE [dbo].[tbl_userRole] WITH CHECK CHECK CONSTRAINT [FK_tbl_userRole_tbl_users_UserId];

ALTER TABLE [dbo].[tbl_address] WITH CHECK CHECK CONSTRAINT [FK_tbl_address_tbl_taxPayer_OwnerId];

ALTER TABLE [dbo].[tbl_company] WITH CHECK CHECK CONSTRAINT [FK_tbl_company_tbl_taxpayerCategory_TaxPayerCatgeoryId];

ALTER TABLE [dbo].[tbl_companyItem] WITH CHECK CHECK CONSTRAINT [FK_tbl_companyItem_tbl_item_ItemId];

ALTER TABLE [dbo].[tbl_companyItem] WITH CHECK CHECK CONSTRAINT [FK_tbl_companyItem_tbl_taxPayer_TaxpayerId];

ALTER TABLE [dbo].[tbl_demandNoticeArrears] WITH CHECK CHECK CONSTRAINT [FK_tbl_demandNoticeArrears_tbl_item_ItemId];

ALTER TABLE [dbo].[tbl_demandNoticeArrears] WITH CHECK CHECK CONSTRAINT [FK_tbl_demandNoticeArrears_tbl_taxPayer_TaxpayerId];

ALTER TABLE [dbo].[tbl_demandNoticePaymentHistory] WITH CHECK CHECK CONSTRAINT [FK_tbl_demandNoticePaymentHistory_tbl_bank_BankId];

ALTER TABLE [dbo].[tbl_demandNoticePenalty] WITH CHECK CHECK CONSTRAINT [FK_tbl_demandNoticePenalty_tbl_item_ItemId];

ALTER TABLE [dbo].[tbl_demandNoticePenalty] WITH CHECK CHECK CONSTRAINT [FK_tbl_demandNoticePenalty_tbl_taxPayer_TaxpayerId];

ALTER TABLE [dbo].[tbl_demandNoticeTaxpayers] WITH CHECK CHECK CONSTRAINT [FK_tbl_demandNoticeTaxpayers_tbl_demandnotice_DnId];

ALTER TABLE [dbo].[tbl_domain] WITH CHECK CHECK CONSTRAINT [FK_tbl_domain_tbl_state_StateId];

ALTER TABLE [dbo].[tbl_item] WITH CHECK CHECK CONSTRAINT [FK_tbl_item_tbl_lcda_LcdaId];

ALTER TABLE [dbo].[tbl_itempenalty] WITH CHECK CHECK CONSTRAINT [FK_tbl_itempenalty_tbl_item_ItemId];

ALTER TABLE [dbo].[tbl_lcda] WITH CHECK CHECK CONSTRAINT [FK_tbl_lcda_tbl_domain_DomainId];

ALTER TABLE [dbo].[tbl_role] WITH CHECK CHECK CONSTRAINT [FK_tbl_role_tbl_lcda_DomainId];

ALTER TABLE [dbo].[tbl_state] WITH CHECK CHECK CONSTRAINT [FK_tbl_state_tbl_country_CountryId];

ALTER TABLE [dbo].[tbl_street] WITH CHECK CHECK CONSTRAINT [FK_tbl_street_tbl_ward_WardId];

ALTER TABLE [dbo].[tbl_taxPayer] WITH CHECK CHECK CONSTRAINT [FK_tbl_taxPayer_tbl_company_CompanyId];

ALTER TABLE [dbo].[tbl_taxPayer] WITH CHECK CHECK CONSTRAINT [FK_tbl_taxPayer_tbl_street_StreetId];

ALTER TABLE [dbo].[tbl_taxPayer] WITH CHECK CHECK CONSTRAINT [FK_tbl_taxPayer_tbl_address_AddressId];

ALTER TABLE [dbo].[tbl_ward] WITH CHECK CHECK CONSTRAINT [FK_tbl_ward_tbl_lcda_LcdaId];

ALTER TABLE [dbo].[tbl_bank_lcda] WITH CHECK CHECK CONSTRAINT [FK_tbl_bank_lcda_tbl_bank_BankId];

ALTER TABLE [dbo].[tbl_bank_lcda] WITH CHECK CHECK CONSTRAINT [FK_tbl_bank_lcda_tbl_lcda_LcdaId];

ALTER TABLE [dbo].[tbl_rolePermission] WITH CHECK CHECK CONSTRAINT [FK_tbl_rolePermission_tbl_permission_PermissionId];

ALTER TABLE [dbo].[tbl_rolePermission] WITH CHECK CHECK CONSTRAINT [FK_tbl_rolePermission_tbl_role_RoleId];

ALTER TABLE [dbo].[tbl_sector] WITH CHECK CHECK CONSTRAINT [FK_tbl_sector_tbl_lcda_LcdaId];

ALTER TABLE [dbo].[tbl_userdomain] WITH CHECK CHECK CONSTRAINT [FK_tbl_userdomain_tbl_domain_DomainId];

ALTER TABLE [dbo].[tbl_userdomain] WITH CHECK CHECK CONSTRAINT [FK_tbl_userdomain_tbl_users_UserId];


GO
PRINT N'Update complete.';


GO
